### ISSUE TITLE
Streaming inference 

### ISSUE THREAD

**Issue by pport997** [scart97/quartznet-android#1]
Hi, I'm trying to do streaming inference on the quartznet model created using your library. but, the outputs are garbage when I tried to implement it using the official pytorch android demo. how do i go about it?

**Comment by scart97** [comment]
I don't have experience with streaming models, so my knowledge is limited here. How much data are you accumulating before running inference? With a small window the outputs will be garbage indeed, as there's not enough context for the model to predict correctly

**Comment by pport997** [comment]
it's working alright with 2 second chunks
